# Generated by Django 5.2.10 on 2026-01-09 00:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PackConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=0, max_digits=10)),
                ('extra_slots_cuentas', models.IntegerField(default=0)),
                ('extra_gb', models.FloatField(default=0)),
                ('extra_notas', models.IntegerField(default=0)),
                ('extra_recordatorios', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PlanConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('precio_mensual', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('slots_cuentas_base', models.IntegerField(default=10)),
                ('limite_gb_base', models.FloatField(default=2.0)),
                ('slots_notas_base', models.IntegerField(default=5)),
                ('slots_recordatorios_base', models.IntegerField(default=1)),
                ('permite_sincronizacion_calendario', models.BooleanField(default=False)),
                ('sin_anuncios', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta_seguridad', models.CharField(blank=True, max_length=255, null=True)),
                ('respuesta_seguridad', models.CharField(blank=True, max_length=255, null=True)),
                ('pin_boveda', models.CharField(blank=True, max_length=128, null=True)),
                ('extra_slots_cuentas', models.IntegerField(default=0)),
                ('extra_gb_almacenamiento', models.FloatField(default=0)),
                ('extra_slots_notas', models.IntegerField(default=0)),
                ('extra_slots_recordatorios', models.IntegerField(default=0)),
                ('total_anuncios_vistos', models.IntegerField(default=0)),
                ('anuncios_vistos_hoy', models.IntegerField(default=0)),
                ('ultima_vez_anuncio', models.DateTimeField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cuentas.planconfig')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
            ],
            options={
                'verbose_name': '📊 Métrica de Negocio',
                'verbose_name_plural': '📊 DASHBOARD Y MÉTRICAS',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cuentas.profile',),
        ),
    ]
