# Generated by Django 5.2.10 on 2026-01-11 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0003_vaultfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('mensaje', models.TextField(help_text='Puedes usar saltos de línea.')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('expira_en', models.DateTimeField(help_text='Fecha y hora en que dejará de mostrarse el anuncio.')),
                ('tipo', models.CharField(choices=[('info', 'Información'), ('promo', 'Promoción / Pack'), ('alerta', 'Alerta / Pánico')], default='info', max_length=20)),
                ('activo', models.BooleanField(default=True, help_text='Desactívalo manualmente si quieres ocultarlo antes de tiempo.')),
            ],
            options={
                'verbose_name': '📢 Anuncio de Sistema',
                'verbose_name_plural': '📢 Anuncios de Sistema',
                'ordering': ['-creado_en'],
            },
        ),
    ]
