# Generated by Django 5.2.10 on 2026-01-12 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0004_anuncio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='site_icon_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
