# Generated by Django 5.2.10 on 2026-01-12 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0005_alter_account_site_icon_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pin_boveda',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pregunta_seguridad',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='respuesta_seguridad',
            field=models.TextField(blank=True, null=True),
        ),
    ]
