# Generated by Django 5.2.10 on 2026-01-17 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0006_alter_profile_pin_boveda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='intentos_fallidos',
            field=models.IntegerField(default=0),
        ),
    ]
