# Generated by Django 5.2.10 on 2026-02-07 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0007_profile_intentos_fallidos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboard',
            options={'verbose_name': 'Métrica de Negocio', 'verbose_name_plural': 'DASHBOARD Y MÉTRICAS'},
        ),
        migrations.AddField(
            model_name='profile',
            name='theme',
            field=models.CharField(default='light', help_text="Preferencia de tema: 'light' o 'dark'", max_length=10),
        ),
    ]
