# Generated by Django 5.2.10 on 2026-02-07 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0008_alter_dashboard_options_profile_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='theme',
            field=models.CharField(default='dark', help_text="Preferencia de tema: 'light' o 'dark'", max_length=10),
        ),
    ]
